ci(actions): replace deprecated set-output command
moneymeets/action-heroku-deploy pull request #10
Opened 2022-11-16 11:31 UTC by felix11h

Replacing the deprecated set-output command as discussed in MD-6382. If I understand things correctly, a simple print() is no longer sufficient and we now need to use subprocess.run(). Do you also see it this way, @marns93?

2022-11-17 08:26 UTC, marns93 requested changes
It seems strange to be to use `subprocess` and `echo`, but it works.
I proposed another solution.

But anyways we can think about removing the version output completely. It is not used anymore on our side, but I'm not sure if somebody else is using this, because it is a public action.

2022-11-17 08:26 UTC, marns93 commented on deploy_heroku.py
> +    subprocess.run(f"echo 'release_version={latest_heroku_release.version}' >> $GITHUB_OUTPUT", check=True, shell=True)
Alternative to your solution can be:

```suggestion
    with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
        print(f"release_version={latest_heroku_release.version}", file=fh)
```

2022-11-17 08:52 UTC, felix11h commented on deploy_heroku.py
> +    subprocess.run(f"echo 'release_version={latest_heroku_release.version}' >> $GITHUB_OUTPUT", check=True, shell=True)
Thanks for the feedback. I don't have a strong opinion on this, and I'm also ok with removing the version output if we no longer needed.

2022-11-17 12:43 UTC, marns93 commented on deploy_heroku.py
> +    subprocess.run(f"echo 'release_version={latest_heroku_release.version}' >> $GITHUB_OUTPUT", check=True, shell=True)
Okay I searched on GitHub at it seems that no public repository is using it, but we don't know if someone uses it in a private repo:
https://github.com/search?q=%22moneymeets%2Faction-heroku-deploy%22&type=code

I think we can remove it. If there is somebody using it, we will be notified.

Please remove it also from https://github.com/moneymeets/action-heroku-deploy/blob/master/action.yml#L14.

The `id` in some of our repositories can be removed as well (e.g.) https://github.com/moneymeets/moneymeets-backoffice/blob/1882976a0c119b3b5f68144412cbe4e4216724d2/.github/workflows/deploy.yml#L20, but this can be done independently.

2022-11-18 09:29 UTC, felix11h commented on deploy_heroku.py
> +    subprocess.run(f"echo 'release_version={latest_heroku_release.version}' >> $GITHUB_OUTPUT", check=True, shell=True)
I have removed the release version output. I will check our Heroku deployment workflows and will open pull requests to remove the `id`, where it is present.

2022-11-18 09:31 UTC, marns93 requested changes
I think the id `deploy-and-get-release-version` can be removed as well in `action.yml`. It was used to access the output variable.

2022-11-18 09:36 UTC, marns93 approved these changes
Thank you! :+1:

2022-11-18 09:38 UTC, felix11h commented
/rebase

2022-11-18 09:41 UTC, merged